using Graficas.Edges;
using System.Collections.Generic;
using Graficas.Rutas;

namespace Graficas.Grafo
{
	/// <summary>
	/// Un grafo en el que se pueden leer y escribir nodos y aristas
	/// </summary>
	public interface IGrafo<T>
	{
		/// <summary>
		/// Clears the entire graph.
		/// </summary>
		void Clear ();

		/// <summary>
		/// Gets the edge bewteen two nodex.
		/// </summary>
		IEdge<T> this[T desde, T hasta] { get; }

		/// <summary>
		/// Nodes collection.
		/// </summary>
		ICollection<T> Nodes { get; }

		/// <summary>
		/// Gets the existing edges.
		/// </summary>
		ICollection<IEdge<T>> Edges ();

		/// <summary>
		/// Gets the neighborhood of a node.
		/// </summary>
		ICollection<T> Neighborhood (T node);

		/// <summary>
		/// Converts a sequence of nodes into a path.
		/// </summary>
		IRuta<T> ToPath (IEnumerable<T> seq);

		/// <summary>
		/// Gets the subgraph generated by a collection of nodes
		/// </summary>
		IGrafo<T> Subgraph (IEnumerable<T> nodeSubset);
	}
}